import {Response} from 'express'; import {z} from 'zod'; import {Post} from '../models/Post'; import {AuthRequest} from '../middleware/auth'; import {countWords,normalizeTags,slugify} from '../utils/validation'; import {uploadBuffer,destroyMedia} from '../services/cloudinary';
const bodySchema=z.object({description:z.string().trim(),anime:z.string().trim().min(1).max(100)});
async function uniqueSlug(anime:string){const base=slugify(anime)||'post';let slug=`${base}-${Math.random().toString(36).slice(2,8)}`;while(await Post.exists({slug}))slug=`${base}-${Math.random().toString(36).slice(2,8)}`;return slug;}
export async function createPost(req:AuthRequest,res:Response){try{const data=bodySchema.parse(req.body);if(countWords(data.description)<10)return res.status(400).json({message:'Description must contain at least 10 words.'});if(!req.file)return res.status(400).json({message:'Please upload an image or video.'});const mediaType=req.file.mimetype.startsWith('video/')?'video':'image';
const uploaded=await uploadBuffer(req.file.buffer,mediaType,`anime-platform/${mediaType}s`);
if(mediaType==='video'){const duration=Number(uploaded.duration);if(!Number.isFinite(duration)||duration<5||duration>60){try{await destroyMedia(uploaded.public_id,'video');}catch{};return res.status(400).json({message:!Number.isFinite(duration)?'Unable to validate video duration. Please try another video.':duration<5?'Video must be at least 5 seconds long.':'Video cannot exceed 60 seconds.'});}}const tags=normalizeTags(req.body.tags?JSON.parse(req.body.tags):[]);const post=await Post.create({authorId:req.authorId,mediaType,mediaUrl:uploaded.secure_url,mediaPublicId:uploaded.public_id,description:data.description,anime:data.anime,tags,slug:await uniqueSlug(data.anime),deletedAt:null});return res.status(201).json({post});}catch(e:any){return res.status(400).json({message:e?.issues?.[0]?.message??e.message??'Unable to create post.'});}}
export async function listPosts(req:AuthRequest,res:Response){const limit=Math.min(Math.max(Number(req.query.limit)||8,1),20);const cursor=typeof req.query.cursor==='string'?new Date(req.query.cursor):null;const filter:any={deletedAt:null};if(cursor&&!Number.isNaN(cursor.getTime()))filter.createdAt={$lt:cursor};const posts=await Post.find(filter).sort({createdAt:-1}).limit(limit).populate('authorId','name country profileImage');const nextCursor=posts.length===limit?posts[posts.length-1].createdAt.toISOString():null;res.json({posts,nextCursor});}
export async function getPost(req:AuthRequest,res:Response){const post=await Post.findOne({slug:req.params.slug,deletedAt:null}).populate('authorId','name country profileImage');if(!post)return res.status(404).json({message:'Post not found.'});res.json({post});}
export async function updatePost(req:AuthRequest,res:Response){const post=await Post.findOne({_id:req.params.id,authorId:req.authorId,deletedAt:null});if(!post)return res.status(404).json({message:'Post not found.'});const data=bodySchema.parse(req.body);if(countWords(data.description)<10)return res.status(400).json({message:'Description must contain at least 10 words.'});post.description=data.description;post.anime=data.anime;post.tags=normalizeTags(req.body.tags?JSON.parse(req.body.tags):[]);if(req.file){await destroyMedia(post.mediaPublicId,post.mediaType);const type=req.file.mimetype.startsWith('video/')?'video':'image';const u=await uploadBuffer(req.file.buffer,type,`anime-platform/${type}s`);post.mediaType=type;post.mediaUrl=u.secure_url;post.mediaPublicId=u.public_id;}await post.save();res.json({post});}
export async function deletePost(req:AuthRequest,res:Response){const post=await Post.findOne({_id:req.params.id,authorId:req.authorId,deletedAt:null});if(!post)return res.status(404).json({message:'Post not found.'});post.deletedAt=new Date();await post.save();try{await destroyMedia(post.mediaPublicId,post.mediaType);}catch{}res.json({message:'Post deleted.'});}
export async function myPosts(req:AuthRequest,res:Response){const posts=await Post.find({authorId:req.authorId}).sort({createdAt:-1});res.json({posts});}
